Rewrote README to be clearer
devleague/Buzz-Word-Bingo pull request #5
Opened 2017-12-08 23:02 UTC by taesup

Dropped all reference to how this is a game because it consistently confused students. Instead it's been turned into a tracking system that just keeps track of how many times a specific buzzword was used in a conversation. The "system" can be loaded with up to 5 buzzwords. The "PUT" method is used as a way to mark that a given buzzword was heard and the points should be updated accordingly. The "PUT" response should be the buzzword itself along with the new total score. All other aspects of the exercise was not modified.

2017-12-12 05:34 UTC, jaywon reviewed
LGTM ✅ 

Would be good if another instructor who has gone through this exercise can give ultimate approval. 

Thanks for improving it tho 💯

2017-12-13 02:05 UTC, jesse-copeland requested changes
We need to clarify how a buzzword is scored

2017-12-13 02:05 UTC, mentalgrinds commented on README.md
> +| `PUT /buzzwords` | `{ "buzzWord": String, "heard": Bool }` |  `{ "success": true, newScore: Number }` | Updates a buzzword's heard value. This also marks that a buzzword has been heard and should u
`PUT` to `/buzzword` should modify the existing buzzword model, not score the buzzword. A new endpoint should be created for that.
`newScore:` should be changed to `totalScore`

2017-12-13 02:05 UTC, mentalgrinds commented on README.md
> +For now, it's up to you on how you keep track of the user's score.
A new route should be added the test if a buzzword has been heard.
`PUT` to `/heard` by passing the `{"buzzWord": "Social-Mobile"}, if "Social-Mobile" is a buzzWord that was created using with `POST` to `/buzzwords` then the totalScore would be incremented by the point value of the buzzword, and `{"success": true, "totalScore": 'some inc value'}` will be returned.

2017-12-13 02:05 UTC, mentalgrinds commented on README.md
> +`PUT /buzzwords`:  Updates a buzz word's `heard` property. This also marks that the buzzword has been "heard" in the conversation. Therefore, the total score should be incremented with the score valu
`heard` should not be a property of a buzzWord

2017-12-30 23:25 UTC, merged